### ISSUE TITLE
Denied access to .git

### ISSUE THREAD

**Issue by GingerDD** [PepperPD/edx-pepper-platform#1]
Not able to push repo from GitBash to PepperPD/edx-pepper-platform.

$git remote add <name> git@github.com:PepperPD/edx-pepper-platform.git
or
$git remote add <name> https://github.com/PepperPD/edx-pepper-platform.git

$ git push -u <name> master
Warning: Permanently added 'github.com,192.30.252.131' <RSA> to the list of know hosts.
ERROR: Permission to PepperPD/edx-pepper-platform.git denied to GingerDD.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exist.
![push3](https://f.cloud.github.com/assets/5809498/1531519/e3838ac6-4c66-11e3-82d7-c0959a10acf2.png)

**Comment by chrisrossi** [comment]
Hi Ginger,

I think you will have better luck if you follow the instructions I wrote.  If you do a clone of the repository from GitHub there will be no need to change the origin URL.  You do need to make sure your SSH public key is registered with GitHub so that you can have SSH access to the repository.

Chris

**Comment by GingerDD** [comment]
Thanks Chris for your reply.
I created an organization under my GingerDD accout and asked others to push. We have not problem at all.
While I add them as OWNER, so they have the full access (PULL&PUSH&Admin) to it.
If you created PepperPD for us, are we in the Owners Team page or team management page and what permissions are granted to us?

Ginger

**Comment by chrisrossi** [comment]
I'm not really sure what you're trying to do.  Maybe this is more for @jmarks.

**Comment by jmarks** [comment]
Yes I think the issue was that the repo was not associated with the PepperDev team. That seems fixed. 

Joshua Marks

CTO

Curriki: The Global Education and Learning Community 

jmarks@curriki.org

www.curriki.org 

US 831-685-3511

I welcome you to become a member https://www.curriki.org/xwiki/bin/view/Main/JoinCurriki  of the Curriki community, to follow us on Twitter http://twitter.com/Curriki  and to say hello on our blog http://blog.curriki.org/ , Facebook http://www.facebook.com/pages/Curriki/134427817464  and LinkedIn http://www.linkedin.com/groupInvitation?groupID=1826931&sharedKey=277A033FEF70  communities.

**Comment by GingerDD** [comment]
Thank you all. Yes, the issue is fixed.
